name: CI to start with

on:
  push:
    branches:
      - main
    paths:
      - "app/**"
      - ".github/workflows/ci.yml"
  pull_request:
    branches:
      - main
    paths:
      - "app/**"

env:
  IMAGE_NAME: ghcr.io/anshul-exe/autonomous-cloud-guardian
  NODE_VERSION: "20"

jobs:
  # JOB 1 - ESLint
  lint:
    name: "ESLint"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: node setup
        uses: actions/setup-node@v5
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"
          cache-dependency-path: app/package-lock.json

      - name: installatons
        run: cd app && npm ci

      - name: Run ESLint
        run: cd app && npx eslint index.js --max-warnings=0

      - name: npm audit
        run: cd app && npm audit --audit-level=high

      - name: Build image
        run: docker build -t ${{ env.IMAGE_NAME }}:${{ github.sha }} ./app

      - name: Save image as artifat in tmp
        run: docker save ${{ env.IMAGE_NAME }}:${{ github.sha }} -o /tmp/image.tar

      - name: artifact upload
        uses: actions/upload-artifact@v4
        with:
          name: docker-image-${{ github.sha }}
          path: /tmp/image.tar
          retention-days: 1
